# Generated by Django 4.0.3 on 2022-03-02 09:14

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('articles', '0003_remove_articles_approved_by_articles_approved_at_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='articles',
            name='approved_at',
        ),
        migrations.RemoveField(
            model_name='articles',
            name='reviewer',
        ),
        migrations.AddField(
            model_name='articles',
            name='approved_by',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='approved_by', to=settings.AUTH_USER_MODEL),
        ),
    ]
