# Generated by Django 4.0.3 on 2022-03-02 09:47

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('articles', '0004_remove_articles_approved_at_remove_articles_reviewer_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='articles',
            name='approved_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='approved_by', to=settings.AUTH_USER_MODEL),
        ),
    ]
