# Generated by Django 4.0.3 on 2022-03-02 09:49

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('articles', '0005_alter_articles_approved_by'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='articles',
            name='approved_by',
        ),
        migrations.AddField(
            model_name='articles',
            name='reviewer',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='reviewer', to=settings.AUTH_USER_MODEL),
        ),
    ]
